### PR TITLE
style(line): update length to 120 chars

### PR DESCRIPTION
**Pull request by baptistemesta**

### CODE REVIEW

**Comment by baptistemesta** [comment]
I think it is better to have a limit to 120 in order to ease the code review in github, ease the comparison of files side by side in the IDE.
Also it is the default value in IntelliJ.
What is your opinion?

**Comment by cpuy** [comment]
👍 Awesome !!!!! LGTM

**Comment by laurentleseigneur** [comment]
LGTM

**Comment by educhastenier** [comment]
This impact is huge !!!
All files have to be reformatted !!!
:-1:

**Comment by laurentleseigneur** [comment]
how do i use it by default in IDEA ?

**Comment by baptistemesta** [comment]
@educhastenier I agree there is a big impact. To do the transition we can format only changed line of code. But yep... maybe it's not such a good idea to change it. I'd like to have the formatting rules enforced on each project just like we do it on bonita-elasticsearch:
https://github.com/bonitasoft/bonita-elasticsearch/blob/master/build.gradle#L44
@laurentleseigneur what do you mean? the formatter.xml file?

**Review by educhastenier — COMMENTED** [review]
I fear that we would have MANY merge problems if we start applying that from now on :grimacing:

**Comment by rbioteau** [comment]
For the record we are already using this length in the Studio and I'm happy with it.
We do not have any merge issue.
We do not have made a big bang to reformat all files

Just new code and modified code are reformatted. It is way easier to read PR with this length (no Horizontal scrolling)

**Comment by baptistemesta** [comment]
yep we can do the transition like that. just format modified lines of code.
In the mean time if you format a line of code using max length = 120, then someone else format using max length = 160, the IDE will not rechange the formatting.

**Comment by educhastenier** [comment]
@baptistemesta so you should add the option to reformat only the change line, in the same configuration file

**Comment by cpuy** [comment]
For the record I've also my IDE configured to 120 for 4 years now and I've never seen any issues

**Comment by nchabanoles** [comment]
I am ok with moving the value from 160 to 120. It suits the usage in Github for the review.
I would not do any bigbang as well; only formating the classes when they change. Even better: only format the lines when they are updated.

I want to add, that the current state is already a mix of code respecting this 160 char limit and other code that does not.

Note: I've found the longest line in a java class of one of our modules and you might not believe its size...! 
Hint: this is the ascii code of ȣ

**Comment by cpuy** [comment]
\o/

**Pull request merged**
